//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD_NHAP
    {
        public int MaHD { get; set; }
        public int MaSP { get; set; }
        public int SoLuong { get; set; }
        public double DonGia { get; set; }
        public double ChietKhau { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual HOADON_NHAP HOADON_NHAP { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
