//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CTHD_BAN = new HashSet<CTHD_BAN>();
            this.CTHD_NHAP = new HashSet<CTHD_NHAP>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public int SoLuong { get; set; }
        public double DonGia { get; set; }
        public int MaNCC { get; set; }
        public byte[] HinhAnh { get; set; }
        public string HeDieuHanh { get; set; }
        public int BoNho { get; set; }
        public int Ram { get; set; }
        public string Chip { get; set; }
        public string Camera { get; set; }
        public string MauSac { get; set; }
        public int NamPhatHanh { get; set; }
        public int BaoHanh { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD_BAN> CTHD_BAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTHD_NHAP> CTHD_NHAP { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
    }
}
