//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG
    {
        public int LogID { get; set; }
        public string Username { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string MoTa { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
