//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyShopDienThoaiEntities : DbContext
    {
        public QuanLyShopDienThoaiEntities()
            : base("name=QuanLyShopDienThoaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHD_BAN> CTHD_BAN { get; set; }
        public virtual DbSet<CTHD_NHAP> CTHD_NHAP { get; set; }
        public virtual DbSet<HOADON_BAN> HOADON_BAN { get; set; }
        public virtual DbSet<HOADON_NHAP> HOADON_NHAP { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOG> LOGs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAIKHOAN> TAIKHOANs { get; set; }
    
        [DbFunction("QuanLyShopDienThoaiEntities", "ThongKeDoanhThuSanPham")]
        public virtual IQueryable<ThongKeDoanhThuSanPham_Result> ThongKeDoanhThuSanPham(Nullable<System.DateTime> ngayBatDau, Nullable<System.DateTime> ngayKetThuc)
        {
            var ngayBatDauParameter = ngayBatDau.HasValue ?
                new ObjectParameter("ngayBatDau", ngayBatDau) :
                new ObjectParameter("ngayBatDau", typeof(System.DateTime));
    
            var ngayKetThucParameter = ngayKetThuc.HasValue ?
                new ObjectParameter("ngayKetThuc", ngayKetThuc) :
                new ObjectParameter("ngayKetThuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<ThongKeDoanhThuSanPham_Result>("[QuanLyShopDienThoaiEntities].[ThongKeDoanhThuSanPham](@ngayBatDau, @ngayKetThuc)", ngayBatDauParameter, ngayKetThucParameter);
        }
    
        public virtual ObjectResult<ChiTieuTheoNam_Result> ChiTieuTheoNam(Nullable<int> nam)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTieuTheoNam_Result>("ChiTieuTheoNam", namParameter);
        }
    
        public virtual ObjectResult<ChiTieuTheoNgay_Result> ChiTieuTheoNgay(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTieuTheoNgay_Result>("ChiTieuTheoNgay", startParameter, endParameter);
        }
    
        public virtual ObjectResult<ChiTieuTheoQuy_Result> ChiTieuTheoQuy(string quy)
        {
            var quyParameter = quy != null ?
                new ObjectParameter("quy", quy) :
                new ObjectParameter("quy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ChiTieuTheoQuy_Result>("ChiTieuTheoQuy", quyParameter);
        }
    
        public virtual ObjectResult<DoanhThuTheoNam_Result> DoanhThuTheoNam(Nullable<int> nam)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoanhThuTheoNam_Result>("DoanhThuTheoNam", namParameter);
        }
    
        public virtual ObjectResult<DoanhThuTheoNgay_Result> DoanhThuTheoNgay(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoanhThuTheoNgay_Result>("DoanhThuTheoNgay", startParameter, endParameter);
        }
    
        public virtual ObjectResult<DoanhThuTheoQuy_Result> DoanhThuTheoQuy(string quy)
        {
            var quyParameter = quy != null ?
                new ObjectParameter("quy", quy) :
                new ObjectParameter("quy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DoanhThuTheoQuy_Result>("DoanhThuTheoQuy", quyParameter);
        }
    
        public virtual ObjectResult<HienThiKhachHang_Result> HienThiKhachHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HienThiKhachHang_Result>("HienThiKhachHang");
        }
    
        public virtual ObjectResult<HienThiNhaCungCap_Result> HienThiNhaCungCap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HienThiNhaCungCap_Result>("HienThiNhaCungCap");
        }
    
        public virtual ObjectResult<LayDSKhachHangMuaHangNhieu_Result> LayDSKhachHangMuaHangNhieu(Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDSKhachHangMuaHangNhieu_Result>("LayDSKhachHangMuaHangNhieu", tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<LayDSKhachHangMuaHangNhieuTheoNam_Result> LayDSKhachHangMuaHangNhieuTheoNam(Nullable<int> nam)
        {
            var namParameter = nam.HasValue ?
                new ObjectParameter("nam", nam) :
                new ObjectParameter("nam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDSKhachHangMuaHangNhieuTheoNam_Result>("LayDSKhachHangMuaHangNhieuTheoNam", namParameter);
        }
    
        public virtual ObjectResult<LayDSKhachHangMuaHangNhieuTheoQuy_Result> LayDSKhachHangMuaHangNhieuTheoQuy(Nullable<int> quy)
        {
            var quyParameter = quy.HasValue ?
                new ObjectParameter("quy", quy) :
                new ObjectParameter("quy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDSKhachHangMuaHangNhieuTheoQuy_Result>("LayDSKhachHangMuaHangNhieuTheoQuy", quyParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> LaySoLuongKhachHangChuaMuaHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LaySoLuongKhachHangChuaMuaHang");
        }
    
        public virtual ObjectResult<Nullable<int>> LaySoLuongKhachHangDaMuaHang()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("LaySoLuongKhachHangDaMuaHang");
        }
    
        public virtual ObjectResult<LoadDataByDateInCustomer_Result> LoadDataByDateInCustomer(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoadDataByDateInCustomer_Result>("LoadDataByDateInCustomer", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<LoadDataByDateInSupplier_Result> LoadDataByDateInSupplier(Nullable<System.DateTime> fromDate, Nullable<System.DateTime> toDate)
        {
            var fromDateParameter = fromDate.HasValue ?
                new ObjectParameter("fromDate", fromDate) :
                new ObjectParameter("fromDate", typeof(System.DateTime));
    
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("toDate", toDate) :
                new ObjectParameter("toDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoadDataByDateInSupplier_Result>("LoadDataByDateInSupplier", fromDateParameter, toDateParameter);
        }
    
        public virtual ObjectResult<QLNhaCungCap_Result> QLNhaCungCap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<QLNhaCungCap_Result>("QLNhaCungCap");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int TimKiemKhachHangTheoBoLoc(string columnName, string value)
        {
            var columnNameParameter = columnName != null ?
                new ObjectParameter("columnName", columnName) :
                new ObjectParameter("columnName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiemKhachHangTheoBoLoc", columnNameParameter, valueParameter);
        }
    
        public virtual int TimKiemNhaCungCapTheoBoLoc(string tableName, string columnName, string value)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            var columnNameParameter = columnName != null ?
                new ObjectParameter("columnName", columnName) :
                new ObjectParameter("columnName", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TimKiemNhaCungCapTheoBoLoc", tableNameParameter, columnNameParameter, valueParameter);
        }
    }
}
